# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 25 Nov 2021 20:31:42 +0000
*               @ALL          1
*               @user         8
