<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 25 Nov 2021 20:31:42 +0000
 */
$conf['title'] = 'Hobos\' Bizarre Adventure';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['savedir'] = '/app/dokuwiki/data';
