# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 25 Nov 2021 20:31:42 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

alex:$2y$10$MpJgQlyFlkGZpmDtCtQgTOwV9PxOTmonBPDbwh/1WC5sVva1IBP.K:Alex Meuer:alexmeuer@gmail.com:admin,user
